interface ProductIndex {
    [key: string]: any;
}

export interface Product extends ProductIndex {
    id: string;
    code: string;
    name: string;
    description: string;
    image: string;
    price: number;
    category: string;
    quantity: number;
    inventoryStatus: string;
    rating: number;
}

export const ProductService = {
    getProductsData(): Product[] {
        return [
            {
                id: '1000',
                code: 'f230fh0g3',
                name: 'Bamboo Watch',
                description: 'Product Description',
                image: 'bamboo-watch.jpg',
                price: 65,
                category: 'Accessories',
                quantity: 24,
                inventoryStatus: 'INSTOCK',
                rating: 5,
            },
            {
                id: '1001',
                code: 'nvklal433',
                name: 'Black Watch',
                description: 'Product Description',
                image: 'black-watch.jpg',
                price: 72,
                category: 'Accessories',
                quantity: 61,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1002',
                code: 'zz21cz3c1',
                name: 'Blue Band',
                description: 'Product Description',
                image: 'blue-band.jpg',
                price: 79,
                category: 'Fitness',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
            },
            {
                id: '1003',
                code: '244wgerg2',
                name: 'Blue T-Shirt',
                description: 'Product Description',
                image: 'blue-t-shirt.jpg',
                price: 29,
                category: 'Clothing',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 5,
            },
            {
                id: '1004',
                code: 'h456wer53',
                name: 'Bracelet',
                description: 'Product Description',
                image: 'bracelet.jpg',
                price: 15,
                category: 'Accessories',
                quantity: 73,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1005',
                code: 'av2231fwg',
                name: 'Brown Purse',
                description: 'Product Description',
                image: 'brown-purse.jpg',
                price: 120,
                category: 'Accessories',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
            },
            {
                id: '1006',
                code: 'bib36pfvm',
                name: 'Chakra Bracelet',
                description: 'Product Description',
                image: 'chakra-bracelet.jpg',
                price: 32,
                category: 'Accessories',
                quantity: 5,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
            },
            {
                id: '1007',
                code: 'mbvjkgip5',
                name: 'Galaxy Earrings',
                description: 'Product Description',
                image: 'galaxy-earrings.jpg',
                price: 34,
                category: 'Accessories',
                quantity: 23,
                inventoryStatus: 'INSTOCK',
                rating: 5,
            },
            {
                id: '1008',
                code: 'vbb124btr',
                name: 'Game Controller',
                description: 'Product Description',
                image: 'game-controller.jpg',
                price: 99,
                category: 'Electronics',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 4,
            },
            {
                id: '1009',
                code: 'cm230f032',
                name: 'Gaming Set',
                description: 'Product Description',
                image: 'gaming-set.jpg',
                price: 299,
                category: 'Electronics',
                quantity: 63,
                inventoryStatus: 'INSTOCK',
                rating: 3,
            },
            {
                id: '1010',
                code: 'plb34234v',
                name: 'Gold Phone Case',
                description: 'Product Description',
                image: 'gold-phone-case.jpg',
                price: 24,
                category: 'Accessories',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
            },
            {
                id: '1011',
                code: '4920nnc2d',
                name: 'Green Earbuds',
                description: 'Product Description',
                image: 'green-earbuds.jpg',
                price: 89,
                category: 'Electronics',
                quantity: 23,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1012',
                code: '250vm23cc',
                name: 'Green T-Shirt',
                description: 'Product Description',
                image: 'green-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 74,
                inventoryStatus: 'INSTOCK',
                rating: 5,
            },
            {
                id: '1013',
                code: 'fldsmn31b',
                name: 'Grey T-Shirt',
                description: 'Product Description',
                image: 'grey-t-shirt.jpg',
                price: 48,
                category: 'Clothing',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 3,
            },
            {
                id: '1014',
                code: 'waas1x2as',
                name: 'Headphones',
                description: 'Product Description',
                image: 'headphones.jpg',
                price: 175,
                category: 'Electronics',
                quantity: 8,
                inventoryStatus: 'LOWSTOCK',
                rating: 5,
            },
            {
                id: '1015',
                code: 'vb34btbg5',
                name: 'Light Green T-Shirt',
                description: 'Product Description',
                image: 'light-green-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 34,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1016',
                code: 'k8l6j58jl',
                name: 'Lime Band',
                description: 'Product Description',
                image: 'lime-band.jpg',
                price: 79,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 3,
            },
            {
                id: '1017',
                code: 'v435nn85n',
                name: 'Mini Speakers',
                description: 'Product Description',
                image: 'mini-speakers.jpg',
                price: 85,
                category: 'Clothing',
                quantity: 42,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1018',
                code: '09zx9c0zc',
                name: 'Painted Phone Case',
                description: 'Product Description',
                image: 'painted-phone-case.jpg',
                price: 56,
                category: 'Accessories',
                quantity: 41,
                inventoryStatus: 'INSTOCK',
                rating: 5,
            },
            {
                id: '1019',
                code: 'mnb5mb2m5',
                name: 'Pink Band',
                description: 'Product Description',
                image: 'pink-band.jpg',
                price: 79,
                category: 'Fitness',
                quantity: 63,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1020',
                code: 'r23fwf2w3',
                name: 'Pink Purse',
                description: 'Product Description',
                image: 'pink-purse.jpg',
                price: 110,
                category: 'Accessories',
                quantity: 0,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 4,
            },
            {
                id: '1021',
                code: 'pxpzczo23',
                name: 'Purple Band',
                description: 'Product Description',
                image: 'purple-band.jpg',
                price: 79,
                category: 'Fitness',
                quantity: 6,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
            },
            {
                id: '1022',
                code: '2c42cb5cb',
                name: 'Purple Gemstone Necklace',
                description: 'Product Description',
                image: 'purple-gemstone-necklace.jpg',
                price: 45,
                category: 'Accessories',
                quantity: 62,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1023',
                code: '5k43kkk23',
                name: 'Purple T-Shirt',
                description: 'Product Description',
                image: 'purple-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 5,
            },
            {
                id: '1024',
                code: 'lm2tny2k4',
                name: 'Shoes',
                description: 'Product Description',
                image: 'shoes.jpg',
                price: 64,
                category: 'Clothing',
                quantity: 0,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1025',
                code: 'nbm5mv45n',
                name: 'Sneakers',
                description: 'Product Description',
                image: 'sneakers.jpg',
                price: 78,
                category: 'Clothing',
                quantity: 52,
                inventoryStatus: 'INSTOCK',
                rating: 4,
            },
            {
                id: '1026',
                code: 'zx23zc42c',
                name: 'Teal T-Shirt',
                description: 'Product Description',
                image: 'teal-t-shirt.jpg',
                price: 49,
                category: 'Clothing',
                quantity: 3,
                inventoryStatus: 'LOWSTOCK',
                rating: 3,
            },
            {
                id: '1027',
                code: 'acvx872gc',
                name: 'Yellow Earbuds',
                description: 'Product Description',
                image: 'yellow-earbuds.jpg',
                price: 89,
                category: 'Electronics',
                quantity: 35,
                inventoryStatus: 'INSTOCK',
                rating: 3,
            },
            {
                id: '1028',
                code: 'tx125ck42',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yoga-mat.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 5,
            },
            {
                id: '1029',
                code: 'gwuby345v',
                name: 'Yoga Set',
                description: 'Product Description',
                image: 'yoga-set.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 8,
            },
            {
                id: '1030',
                code: 'q2135a',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistance-bands.jpg',
                price: 11,
                category: 'Fitness',
                quantity: 42,
                inventoryStatus: 'INSTOCK',
                rating: 4.9,
            },
            {
                id: '1031',
                code: 'b3nd4y',
                name: 'Running Shoes',
                description: 'Product Description',
                image: 'running-shoes.jpg',
                price: 60,
                category: 'Athletic',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 9.3,
            },
            {
                id: '1032',
                code: 'h8fj23',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yoga-mat.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 35,
                inventoryStatus: 'INSTOCK',
                rating: 7.5,
            },
            {
                id: '1033',
                code: 'p9kd2l',
                name: 'Dumbbell Set',
                description: 'Product Description',
                image: 'dumbbell-set.jpg',
                price: 45,
                category: 'Fitness',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 8.7,
            },
            {
                id: '1034',
                code: 'o2rtn7',
                name: 'Fitness Tracker',
                description: 'Product Description',
                image: 'fitness-tracker.jpg',
                price: 80,
                category: 'Fitness',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 8.9,
            },
            {
                id: '1035',
                code: 'g5pl9q',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jump-rope.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 30,
                inventoryStatus: 'INSTOCK',
                rating: 7.2,
            },
            {
                id: '1036',
                code: 's4j9n2',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistance-bands.jpg',
                price: 25,
                category: 'Fitness',
                quantity: 40,
                inventoryStatus: 'INSTOCK',
                rating: 8.4,
            },
            {
                id: '1037',
                code: 'k3m8h1',
                name: 'Boxing Gloves',
                description: 'Product Description',
                image: 'boxing-gloves.jpg',
                price: 50,
                category: 'Boxing',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 9.0,
            },
            {
                id: '1038',
                code: 't9l3p5',
                name: 'Water Bottle',
                description: 'Product Description',
                image: 'water-bottle.jpg',
                price: 10,
                category: 'Accessories',
                quantity: 50,
                inventoryStatus: 'INSTOCK',
                rating: 6.8,
            },
            {
                id: '1040',
                code: 'r5s3t6',
                name: 'Tennis Racket',
                description: 'Product Description',
                image: 'tennis-racket.jpg',
                price: 75,
                category: 'Tennis',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },

            {
                id: '1041',
                code: 'f2d8a4',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yoga-mat.jpg',
                price: 30,
                category: 'Yoga',
                quantity: 40,
                inventoryStatus: 'INSTOCK',
                rating: 7.2,
            },

            {
                id: '1042',
                code: 'p9k4s7',
                name: 'Running Shoes',
                description: 'Product Description',
                image: 'running-shoes.jpg',
                price: 90,
                category: 'Running',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 9.3,
            },

            {
                id: '1043',
                code: 'h5u2r9',
                name: 'Dumbbell Set',
                description: 'Product Description',
                image: 'dumbbell-set.jpg',
                price: 120,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 8.9,
            },

            {
                id: '1044',
                code: 'm3b8f7',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jump-rope.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 30,
                inventoryStatus: 'INSTOCK',
                rating: 7.5,
            },
            {
                id: '1045',
                code: 'y3t5p2',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistance-bands.jpg',
                price: 25,
                category: 'Fitness',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 9.2,
            },
            {
                id: '1046',
                code: 'p8k2j4',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yoga-mat.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 8.7,
            },
            {
                id: '1047',
                code: 'w2n9j5',
                name: 'Medicine Ball',
                description: 'Product Description',
                image: 'medicine-ball.jpg',
                price: 40,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 9.0,
            },
            {
                id: '1048',
                code: 'r5s8h2',
                name: 'Balance Board',
                description: 'Product Description',
                image: 'balance-board.jpg',
                price: 50,
                category: 'Fitness',
                quantity: 8,
                inventoryStatus: 'INSTOCK',
                rating: 8.8,
            },
            {
                id: '1049',
                code: 't6m3k9',
                name: 'Foam Roller',
                description: 'Product Description',
                image: 'foam-roller.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },
            {
                id: '1050',
                code: 'q9l7t4',
                name: 'Workout Bench',
                description: 'Product Description',
                image: 'workout-bench.jpg',
                price: 150,
                category: 'Fitness',
                quantity: 5,
                inventoryStatus: 'INSTOCK',
                rating: 9.5,
            },
            {
                id: '1051',
                code: 'r3n9p2',
                name: 'Dumbbell Set',
                description: 'Product Description',
                image: 'dumbbell-set.jpg',
                price: 100,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 9.0,
            },
            {
                id: '1052',
                code: 's2w8f3',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yoga-mat.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 8.0,
            },
            {
                id: '1053',
                code: 'u4t5w2',
                name: 'Resistance Bands Set',
                description: 'Product Description',
                image: 'resistance-bands-set.jpg',
                price: 40,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },
            {
                id: '1054',
                code: 'v6x8y3',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jump-rope.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 30,
                inventoryStatus: 'INSTOCK',
                rating: 7.5,
            },
            {
                id: '1055',
                code: 'w9z1q5',
                name: 'Kettlebell',
                description: 'Product Description',
                image: 'kettlebell.jpg',
                price: 50,
                category: 'Fitness',
                quantity: 8,
                inventoryStatus: 'INSTOCK',
                rating: 9.0,
            },
            {
                id: '1056',
                code: 'p4a7t9',
                name: 'Treadmill',
                description: 'Product Description',
                image: 'treadmill.jpg',
                price: 500,
                category: 'Fitness',
                quantity: 2,
                inventoryStatus: 'INSTOCK',
                rating: 9.5,
            },
            {
                id: '1057',
                code: 'b2p3y8',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yogamat.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },

            {
                id: '1058',
                code: 'r6s2c4',
                name: 'Dumbbells',
                description: 'Product Description',
                image: 'dumbbells.jpg',
                price: 70,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 8.0,
            },

            {
                id: '1059',
                code: 'm8d4f6',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jumprope.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 9.0,
            },

            {
                id: '1060',
                code: 's5t9w1',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistancebands.jpg',
                price: 25,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },

            {
                id: '1061',
                code: 'j9m3x7',
                name: 'Exercise Ball',
                description: 'Product Description',
                image: 'exerciseball.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 18,
                inventoryStatus: 'INSTOCK',
                rating: 8.0,
            },

            {
                id: '1062',
                code: 't8p4q6',
                name: 'Fitness Tracker',
                description: 'Product Description',
                image: 'fitnesstracker.jpg',
                price: 100,
                category: 'Fitness',
                quantity: 5,
                inventoryStatus: 'INSTOCK',
                rating: 9.5,
            },
            {
                id: '1063',
                code: 'y5n2o1',
                name: 'Dumbbell Set',
                description: 'Product Description',
                image: 'dumbbellset.jpg',
                price: 50,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 7.8,
            },

            {
                id: '1064',
                code: 'r3s5a2',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yogamat.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },

            {
                id: '1065',
                code: 'k2h8e4',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jumprope.jpg',
                price: 10,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 7.0,
            },

            {
                id: '1066',
                code: 'w9l6u3',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistancebands.jpg',
                price: 25,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 8.2,
            },

            {
                id: '1067',
                code: 'v4n8a9',
                name: 'Treadmill',
                description: 'Product Description',
                image: 'treadmill.jpg',
                price: 500,
                category: 'Fitness',
                quantity: 3,
                inventoryStatus: 'INSTOCK',
                rating: 9.0,
            },

            {
                id: '1068',
                code: 'm3z4y1',
                name: 'Protein Powder',
                description: 'Product Description',
                image: 'proteinpowder.jpg',
                price: 40,
                category: 'Fitness',
                quantity: 8,
                inventoryStatus: 'INSTOCK',
                rating: 8.7,
            },

            {
                id: '1069',
                code: 'p7t3q2',
                name: 'Boxing Gloves',
                description: 'Product Description',
                image: 'boxinggloves.jpg',
                price: 60,
                category: 'Fitness',
                quantity: 6,
                inventoryStatus: 'INSTOCK',
                rating: 8.9,
            },
            {
                id: '1070',
                code: 'w2x1z6',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yogamat.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 9.2,
            },
            {
                id: '1071',
                code: 'r5t9y4',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistancebands.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },
            {
                id: '1072',
                code: 'q1w7e4',
                name: 'Dumbbell Set',
                description: 'Product Description',
                image: 'dumbbellset.jpg',
                price: 80,
                category: 'Fitness',
                quantity: 4,
                inventoryStatus: 'INSTOCK',
                rating: 9.5,
            },
            {
                id: '1073',
                code: 'u8i2o6',
                name: 'Treadmill',
                description: 'Product Description',
                image: 'treadmill.jpg',
                price: 500,
                category: 'Fitness',
                quantity: 2,
                inventoryStatus: 'INSTOCK',
                rating: 9.8,
            },
            {
                id: '1074',
                code: 'a3s6d8',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jumprope.jpg',
                price: 10,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 8.3,
            },
            {
                id: '1075',
                code: 'k4j9h2',
                name: 'Foam Roller',
                description: 'Product Description',
                image: 'foamroller.jpg',
                price: 25,
                category: 'Fitness',
                quantity: 20,
                inventoryStatus: 'INSTOCK',
                rating: 8.0,
            },

            {
                id: '1076',
                code: 'z2x4c9',
                name: 'Kettlebell',
                description: 'Product Description',
                image: 'kettlebell.jpg',
                price: 35,
                category: 'Fitness',
                quantity: 7,
                inventoryStatus: 'INSTOCK',
                rating: 8.6,
            },
            {
                id: '1077',
                code: 'p9q3r5',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yogamat.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 15,
                inventoryStatus: 'INSTOCK',
                rating: 9.2,
            },
            {
                id: '1078',
                code: 'b6z8d4',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistancebands.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 8.4,
            },
            {
                id: '1079',
                code: 'l7g2s1',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jumprope.jpg',
                price: 10,
                category: 'Fitness',
                quantity: 25,
                inventoryStatus: 'INSTOCK',
                rating: 7.8,
            },
            {
                id: '1080',
                code: 't4r9u7',
                name: 'Dumbbells',
                description: 'Product Description',
                image: 'dumbbells.jpg',
                price: 50,
                category: 'Fitness',
                quantity: 5,
                inventoryStatus: 'LOWSTOCK',
                rating: 9.0,
            },
            {
                id: '1081',
                code: 'k1q8n6',
                name: 'Medicine Ball',
                description: 'Product Description',
                image: 'medicineball.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 8.9,
            },
            {
                id: '1082',
                code: 'h5m7l3',
                name: 'Exercise Bike',
                description: 'Product Description',
                image: 'exercisebike.jpg',
                price: 200,
                category: 'Fitness',
                quantity: 3,
                inventoryStatus: 'LOWSTOCK',
                rating: 9.5,
            },
            {
                id: '1083',
                code: 's3n8p6',
                name: 'Treadmill',
                description: 'Product Description',
                image: 'treadmill.jpg',
                price: 500,
                category: 'Fitness',
                quantity: 2,
                inventoryStatus: 'OUTOFSTOCK',
                rating: 9.7,
            },
            {
                id: '1084',
                code: 'v6b3q8',
                name: 'Elliptical Trainer',
                description: 'Product Description',
                image: 'ellipticaltrainer.jpg',
                price: 300,
                category: 'Fitness',
                quantity: 4,
                inventoryStatus: 'LOWSTOCK',
                rating: 9.3,
            },
            {
                id: '1085',
                code: 't4s2r9',
                name: 'Exercise Bike',
                description: 'Product Description',
                image: 'exercisebike.jpg',
                price: 250,
                category: 'Fitness',
                quantity: 3,
                inventoryStatus: 'LOWSTOCK',
                rating: 9.0,
            },
            {
                id: '1086',
                code: 'm7n5t2',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yogamat.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'INSTOCK',
                rating: 8.5,
            },
            {
                id: '1087',
                code: 'p5b2t7',
                name: 'Dumbbells Set',
                description: 'Product Description',
                image: 'dumbbells.jpg',
                price: 100,
                category: 'Fitness',
                quantity: 6,
                inventoryStatus: 'LOWSTOCK',
                rating: 8.7,
            },
            {
                id: '1088',
                code: 'k9l3v4',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistancebands.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 8,
                inventoryStatus: 'INSTOCK',
                rating: 8.2,
            },
            {
                id: '1089',
                code: 'q1p7f4',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jumprope.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'INSTOCK',
                rating: 8.0,
            },
            {
                id: '1090',
                code: 'r5k2n8',
                name: 'Foam Roller',
                description: 'Product Description',
                image: 'foamroller.jpg',
                price: 25,
                category: 'Fitness',
                quantity: 5,
                inventoryStatus: 'LOWSTOCK',
                rating: 8.3,
            },
            {
                id: '1091',
                code: 's2f9t8',
                name: 'Weighted Vest',
                description: 'Product Description',
                image: 'weightedvest.jpg',
                price: 40,
                category: 'Fitness',
                quantity: 7,
                inventoryStatus: 'LOWSTOCK',
                rating: 8.6,
            },
            {
                id: '1092',
                code: 'k3j5t9',
                name: 'Yoga Mat',
                description: 'Product Description',
                image: 'yogamat.jpg',
                price: 20,
                category: 'Fitness',
                quantity: 10,
                inventoryStatus: 'HIGHSTOCK',
                rating: 9.2,
            },
            {
                id: '1093',
                code: 'm8g3f2',
                name: 'Resistance Bands',
                description: 'Product Description',
                image: 'resistancebands.jpg',
                price: 15,
                category: 'Fitness',
                quantity: 3,
                inventoryStatus: 'LOWSTOCK',
                rating: 8.0,
            },
            {
                id: '1094',
                code: 'n5h4j7',
                name: 'Jump Rope',
                description: 'Product Description',
                image: 'jumprope.jpg',
                price: 10,
                category: 'Fitness',
                quantity: 8,
                inventoryStatus: 'HIGHSTOCK',
                rating: 7.5,
            },
            {
                id: '1095',
                code: 't7g3h6',
                name: 'Exercise Ball',
                description: 'Product Description',
                image: 'exerciseball.jpg',
                price: 30,
                category: 'Fitness',
                quantity: 12,
                inventoryStatus: 'HIGHSTOCK',
                rating: 8.9,
            },
            {
                id: '1096',
                code: 'r8j2n9',
                name: 'Dumbbell Set',
                description: 'Product Description',
                image: 'dumbbellset.jpg',
                price: 50,
                category: 'Fitness',
                quantity: 4,
                inventoryStatus: 'LOWSTOCK',
                rating: 9.5,
            },
            {
                id: '1097',
                code: 'p4t7h2',
                name: 'Treadmill',
                description: 'Product Description',
                image: 'treadmill.jpg',
                price: 250,
                category: 'Fitness',
                quantity: 2,
                inventoryStatus: 'LOWSTOCK',
                rating: 8.7,
            },
            {
                id: '1098',
                code: 'q2d5t8',
                name: 'Elliptical Machine',
                description: 'Product Description',
                image: 'ellipticalmachine.jpg',
                price: 300,
                category: 'Fitness',
                quantity: 6,
                inventoryStatus: 'HIGHSTOCK',
                rating: 9.0,
            },
            {
                id: '1099',
                code: 'h5f9r7',
                name: 'Stationary Bike',
                description: 'Product Description',
                image: 'stationarybike.jpg',
                price: 200,
                category: 'Fitness',
                quantity: 9,
                inventoryStatus: 'HIGHSTOCK',
                rating: 8.4,
            },
        ];
    },

    getProducts() {
        return Promise.resolve(this.getProductsData());
    },
};
